import { Link } from "@tanstack/react-router";
import { ArrowLeft, Building2, ClipboardCheck, Factory, FileCheck2, Link2, Recycle, Search, Sparkles, Truck, UserRoundCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { MwanShell, PageIntro } from "./MwanShell";

const services = [
  { icon: FileCheck2, title: "التراخيص والتصاريح", text: "إصدار وإدارة تراخيص أنشطة قطاع إدارة النفايات." },
  { icon: ClipboardCheck, title: "التصاريح الإلكترونية", text: "تقديم ومتابعة طلبات التصاريح التشغيلية." },
  { icon: Truck, title: "نظام إدارة النفايات", text: "متابعة عمليات الجمع والنقل والتخلص الآمن." },
  { icon: Building2, title: "دليل مقدمي الخدمات", text: "البحث عن المنشآت المرخصة والخدمات المتاحة." },
];

export function MwanHome() {
  return <MwanShell>
    <section className="border-b border-border bg-section"><div className="mx-auto grid max-w-7xl items-center gap-10 px-4 py-12 sm:px-6 lg:grid-cols-[1.2fr_.8fr] lg:px-8 lg:py-16"><div><span className="text-sm font-bold text-primary">المركز الوطني لإدارة النفايات</span><h1 className="mt-3 max-w-3xl text-3xl font-extrabold leading-[1.5] sm:text-4xl">منظومة متكاملة لقطاع نفايات مستدام واقتصاد دائري فعّال</h1><p className="mt-5 max-w-2xl leading-8 text-muted-foreground">خدمات رقمية تنظّم القطاع، وتدعم الاستثمار، وتُسهم في حماية البيئة وتعظيم الاستفادة من الموارد.</p><div className="mt-7 flex flex-wrap gap-3"><Button asChild size="lg"><Link to="/mwan-link">استعراض الخدمات <ArrowLeft /></Link></Button><Button variant="outline" size="lg">عن المركز</Button></div></div><div className="grid grid-cols-2 gap-3"><div className="border-r-4 border-primary bg-card p-6 shadow-card"><strong className="text-3xl text-primary">+250</strong><p className="mt-2 text-sm text-muted-foreground">خدمة وتصريح رقمي</p></div><div className="border-r-4 border-accent bg-card p-6 shadow-card"><strong className="text-3xl text-primary">13</strong><p className="mt-2 text-sm text-muted-foreground">منطقة مشمولة</p></div><div className="col-span-2 border-r-4 border-success bg-card p-6 shadow-card"><strong className="text-2xl text-primary">نحو اقتصاد دائري</strong><p className="mt-2 text-sm text-muted-foreground">رفع كفاءة إدارة الموارد وتعزيز إعادة الاستخدام</p></div></div></div></section>
    <section className="mx-auto max-w-7xl px-4 py-14 sm:px-6 lg:px-8"><div className="mb-8 flex items-end justify-between gap-4"><div><span className="text-sm font-bold text-primary">الخدمات الإلكترونية</span><h2 className="mt-2 text-2xl font-extrabold">خدمات موان</h2></div><Button variant="link">عرض جميع الخدمات <ArrowLeft /></Button></div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3"><Card className="border-2 border-primary shadow-card"><CardContent className="p-6"><span className="grid size-12 place-items-center rounded-lg bg-primary text-primary-foreground"><Link2 /></span><div className="mt-5 flex items-center gap-2"><h3 className="font-bold">موان لينك</h3><span className="rounded-sm bg-accent px-2 py-1 text-[10px] font-bold text-accent-foreground">خدمة تجريبية</span></div><p className="mt-2 min-h-12 text-sm leading-6 text-muted-foreground">نربط المواد القابلة للاستفادة بالجهات التي تحتاجها.</p><Button asChild className="mt-3"><Link to="/mwan-link">الدخول للخدمة <ArrowLeft /></Link></Button></CardContent></Card>{services.map(({ icon: Icon, title, text }) => <Card key={title} className="border-border shadow-card"><CardContent className="p-6"><span className="grid size-12 place-items-center rounded-lg bg-secondary text-primary"><Icon /></span><h3 className="mt-5 font-bold">{title}</h3><p className="mt-2 min-h-12 text-sm leading-6 text-muted-foreground">{text}</p><Button variant="link" className="mt-3 px-0">الدخول للخدمة <ArrowLeft /></Button></CardContent></Card>)}</div></section>
  </MwanShell>;
}

export function MwanLinkLanding() {
  return <MwanShell><PageIntro title="موان لينك" crumbs={["الخدمات الإلكترونية", "موان لينك"]} description="خدمة ذكية تربط منتجي المواد والنفايات القابلة للاستفادة بالجهات التي تحتاجها، لتعزيز إعادة الاستخدام واسترداد القيمة قبل التخلص منها." /><div className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8"><div className="mb-10 grid gap-5 md:grid-cols-3"><div className="flex gap-4 border-r-4 border-primary bg-section p-5"><Recycle className="mt-1 size-7 shrink-0 text-primary"/><div><strong>إعادة الاستخدام أولًا</strong><p className="mt-1 text-sm leading-6 text-muted-foreground">تحويل المواد المتاحة إلى موارد قابلة للاستفادة.</p></div></div><div className="flex gap-4 border-r-4 border-primary bg-section p-5"><Sparkles className="mt-1 size-7 shrink-0 text-primary"/><div><strong>مطابقة ذكية</strong><p className="mt-1 text-sm leading-6 text-muted-foreground">اقتراح الجهات الأنسب وفق الكمية والحالة والموقع.</p></div></div><div className="flex gap-4 border-r-4 border-primary bg-section p-5"><UserRoundCheck className="mt-1 size-7 shrink-0 text-primary"/><div><strong>تحقق واضح</strong><p className="mt-1 text-sm leading-6 text-muted-foreground">بيان ما تم التحقق منه دون ضمانات غير واقعية.</p></div></div></div><div className="text-center"><h2 className="text-2xl font-extrabold">كيف تريد استخدام الخدمة؟</h2><p className="mt-2 text-muted-foreground">اختر المسار الذي يناسب احتياج منشأتك</p></div><div className="mx-auto mt-8 grid max-w-4xl gap-6 md:grid-cols-2"><Card className="border-border shadow-card"><CardContent className="p-7"><span className="grid size-14 place-items-center rounded-lg bg-secondary text-primary"><Factory className="size-7" /></span><h3 className="mt-5 text-xl font-bold">منتج النفايات</h3><p className="mt-3 min-h-14 text-sm leading-7 text-muted-foreground">لديك مواد أو نفايات قابلة للاستفادة وتريد عرضها للجهات التي تحتاجها.</p><Button asChild className="mt-6 w-full" size="lg"><Link to="/mwan-link/add-material">عرض مادة <ArrowLeft /></Link></Button></CardContent></Card><Card className="border-border shadow-card"><CardContent className="p-7"><span className="grid size-14 place-items-center rounded-lg bg-secondary text-primary"><Search className="size-7" /></span><h3 className="mt-5 text-xl font-bold">مستهلك النفايات</h3><p className="mt-3 min-h-14 text-sm leading-7 text-muted-foreground">تبحث عن مادة أو نفايات قابلة للاستفادة لاستخدامها في نشاطك.</p><Button asChild className="mt-6 w-full" size="lg"><Link to="/mwan-link/materials">البحث عن مادة <ArrowLeft /></Link></Button></CardContent></Card></div><div className="mx-auto mt-10 max-w-4xl border border-border bg-muted p-5 text-sm leading-7"><strong className="text-primary">خدمة ضمن منظومة موان</strong><p className="mt-1 text-muted-foreground">يتم تطبيق متطلبات التحقق والترخيص والنقل بحسب نوع النشاط والأنظمة المعمول بها في موان.</p></div></div></MwanShell>;
}
