import { MapPin, LocateFixed, Minus, Plus } from "lucide-react";
import { useEffect, useMemo, useRef, useState } from "react";

type Point = { id: string; lat: number; lng: number; title: string; detail: string; href?: string };
type Props = { points?: Point[]; value?: { lat: number; lng: number } | null; onSelect?: (point: { lat: number; lng: number }) => void; picker?: boolean; className?: string };
const TILE = 256;
const clampLat = (lat: number) => Math.max(-85.0511, Math.min(85.0511, lat));
function project(lat: number, lng: number, zoom: number) { const size = TILE * 2 ** zoom; const sin = Math.sin(clampLat(lat) * Math.PI / 180); return { x: (lng + 180) / 360 * size, y: (0.5 - Math.log((1 + sin) / (1 - sin)) / (4 * Math.PI)) * size }; }
function unproject(x: number, y: number, zoom: number) { const size = TILE * 2 ** zoom; const lng = x / size * 360 - 180; const n = Math.PI - 2 * Math.PI * y / size; return { lat: 180 / Math.PI * Math.atan(Math.sinh(n)), lng }; }
export function LocationMap({ points = [], value, onSelect, picker = false, className = "" }: Props) {
  const root = useRef<HTMLDivElement>(null); const drag = useRef<{ x: number; y: number; startX: number; startY: number } | null>(null); const dragged = useRef(false);
  const [center, setCenter] = useState({ lat: 24.4, lng: 45.1 }); const [zoom, setZoom] = useState(5); const [hover, setHover] = useState<string | null>(null); const [geoError, setGeoError] = useState(""); const [size, setSize] = useState({ w: 0, h: 360 });
  const actualCenter = center;
  useEffect(() => { if (!root.current) return; const node = root.current; const resize = () => setSize({ w: node.clientWidth, h: node.clientHeight }); resize(); const observer = new ResizeObserver(resize); observer.observe(node); return () => observer.disconnect(); }, []);
  const tiles = useMemo(() => { const c = project(actualCenter.lat, actualCenter.lng, zoom); const cx = Math.floor(c.x / TILE), cy = Math.floor(c.y / TILE); const nx = Math.ceil(size.w / TILE / 2) + 1, ny = Math.ceil(size.h / TILE / 2) + 1; const all = []; for (let x = cx - nx; x <= cx + nx; x++) for (let y = cy - ny; y <= cy + ny; y++) { const max = 2 ** zoom; if (y >= 0 && y < max) all.push({ x, y, left: x * TILE - c.x + size.w / 2, top: y * TILE - c.y + size.h / 2 }); } return all; }, [actualCenter.lat, actualCenter.lng, size.w, size.h, zoom]);
  const pos = (lat: number, lng: number) => { const c = project(actualCenter.lat, actualCenter.lng, zoom), p = project(lat, lng, zoom); return { left: p.x - c.x + size.w / 2, top: p.y - c.y + size.h / 2 }; };
  const choose = (e: React.MouseEvent<HTMLDivElement>) => { if (!picker || !onSelect || !root.current) return; const r = root.current.getBoundingClientRect(), c = project(actualCenter.lat, actualCenter.lng, zoom); const p = unproject(c.x + e.clientX - r.left - r.width / 2, c.y + e.clientY - r.top - r.height / 2, zoom); onSelect(p); };
  const locate = () => { setGeoError(""); if (!navigator.geolocation) { setGeoError("المتصفح لا يدعم تحديد الموقع."); return; } navigator.geolocation.getCurrentPosition(({ coords }) => { const p = { lat: coords.latitude, lng: coords.longitude }; setCenter(p); onSelect?.(p); }, () => setGeoError("تعذر تحديد الموقع. تحقق من إذن الموقع في المتصفح."), { enableHighAccuracy: true, timeout: 12000 }); };
  const down = (e: React.PointerEvent) => { if ((e.target as HTMLElement).closest("button, a")) return; dragged.current = false; drag.current = { x: e.clientX, y: e.clientY, startX: project(actualCenter.lat, actualCenter.lng, zoom).x, startY: project(actualCenter.lat, actualCenter.lng, zoom).y }; (e.currentTarget as HTMLElement).setPointerCapture(e.pointerId); };
  const move = (e: React.PointerEvent) => { if (!drag.current) return; if (Math.abs(e.clientX - drag.current.x) + Math.abs(e.clientY - drag.current.y) > 4) dragged.current = true; const p = unproject(drag.current.startX - (e.clientX - drag.current.x), drag.current.startY - (e.clientY - drag.current.y), zoom); setCenter(p); };
  const stop = () => { drag.current = null; window.setTimeout(() => { dragged.current = false; }, 0); };
  return <div className={`relative overflow-hidden rounded-lg border border-border bg-muted ${className}`}>
    <div ref={root} className={`relative h-[360px] select-none overflow-hidden ${picker ? "cursor-crosshair" : "cursor-grab active:cursor-grabbing"}`} onPointerDown={down} onPointerMove={move} onPointerUp={stop} onPointerCancel={stop} onClick={e => { if (dragged.current) { dragged.current = false; return; } choose(e); }} onWheel={(e) => { if (e.deltaY < -5) setZoom(z => Math.min(18, z + 1)); else if (e.deltaY > 5) setZoom(z => Math.max(3, z - 1)); }} aria-label={picker ? "اختر موقع المادة على الخريطة" : "خريطة المواد المتاحة"}>
      {tiles.map(t => <img key={`${zoom}-${t.x}-${t.y}`} draggable="false" alt="" src={`https://tile.openstreetmap.org/${zoom}/${((t.x % (2 ** zoom)) + 2 ** zoom) % (2 ** zoom)}/${t.y}.png`} className="pointer-events-none absolute max-w-none" style={{ width: TILE, height: TILE, left: t.left, top: t.top }} />)}
      {points.map(p => { const q = pos(p.lat, p.lng); return <div key={p.id} className="absolute z-10 -translate-x-1/2 -translate-y-full" style={{ left: q.left, top: q.top }} onMouseEnter={() => setHover(p.id)} onMouseLeave={() => setHover(null)}><a href={p.href} onClick={e => e.stopPropagation()} className="grid size-9 place-items-center rounded-full border-[3px] border-white bg-primary text-primary-foreground shadow-lg" aria-label={p.title}><MapPin className="size-5" fill="currentColor" /></a>{hover === p.id && <div className="absolute bottom-11 right-1/2 z-20 w-56 translate-x-1/2 rounded-md bg-background p-3 text-right shadow-xl ring-1 ring-border"><strong className="block text-sm">{p.title}</strong><span className="mt-1 block text-xs text-muted-foreground">{p.detail}</span><span className="mt-2 block text-[10px] text-warning">{p.id.startsWith("user-") ? "الموقع الذي حدده المستخدم" : "موقع تجريبي تقريبي"}</span></div>}</div>; })}
      {value && <div className="pointer-events-none absolute z-10 -translate-x-1/2 -translate-y-1/2" style={{ left: pos(value.lat, value.lng).left, top: pos(value.lat, value.lng).top }}><span className="block size-5 rounded-full border-4 border-white bg-red-600 shadow-lg"/></div>}
    </div>
    <div className="absolute left-3 top-3 z-20 grid overflow-hidden rounded-md border border-border bg-background shadow"><button className="grid size-9 place-items-center hover:bg-muted" onClick={() => setZoom(z => Math.min(18,z+1))} aria-label="تكبير"><Plus className="size-4"/></button><button className="grid size-9 place-items-center border-t border-border hover:bg-muted" onClick={() => setZoom(z => Math.max(3,z-1))} aria-label="تصغير"><Minus className="size-4"/></button></div>
    <button className="absolute left-3 top-[94px] z-20 grid size-9 place-items-center rounded-md border border-border bg-background shadow hover:bg-muted" onClick={locate} aria-label="تحديد موقعي"><LocateFixed className="size-4"/></button>
    <div className="flex items-center justify-between gap-3 border-t border-border bg-background px-3 py-2 text-[11px] text-muted-foreground"><span>{picker ? "انقر على الخريطة لتثبيت الموقع، أو استخدم زر موقعي." : "اسحب للتحريك · مرر للتكبير · اضغط العلامة للتفاصيل"}{geoError && <span className="mr-2 text-destructive">{geoError}</span>}</span><a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer" className="shrink-0 underline">© OpenStreetMap</a></div>
  </div>;
}
