import { Link, useNavigate } from "@tanstack/react-router";
import { Check, CheckCircle2, Circle, Clock3, Search, ShieldCheck, Sparkles, Truck, X } from "lucide-react";
import { useMemo, useState } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { MaterialCard } from "./MaterialCard";
import { useMaterials } from "./materials-store";
import { MwanShell, PageIntro } from "./MwanShell";
import { LocationMap } from "./LocationMap";

const filters = ["كل المواد", "خشب", "معدن", "بلاستيك", "كرتون", "مواد بناء", "أخرى"];

export function MaterialsBrowse() {
  const [filter, setFilter] = useState("كل المواد");
  const [query, setQuery] = useState("");
  const { availableMaterials } = useMaterials();
  const shown = useMemo(() => availableMaterials.filter((m) => (filter === "كل المواد" || m.type === filter) && `${m.title} ${m.type} ${m.city}`.includes(query)), [availableMaterials, filter, query]);
  return <MwanShell><PageIntro title="ابحث عن المواد القابلة للاستفادة" crumbs={["وصال", "المواد المتاحة"]} description="استكشف المواد المتاحة بالقرب من منشأتك واطّلع على مستوى التحقق قبل تقديم الطلب." /><div className="mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:px-8"><div className="relative"><Search className="absolute right-4 top-1/2 size-5 -translate-y-1/2 text-muted-foreground"/><Input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="ابحث عن مادة أو مدينة…" className="h-12 bg-card pr-12" /></div><div className="mt-4 flex gap-2 overflow-x-auto pb-2">{filters.map((item) => <Button key={item} size="sm" variant={filter === item ? "default" : "outline"} onClick={() => setFilter(item)}>{item}</Button>)}</div>
      <div className="mt-7"><LocationMap points={availableMaterials.map(m => ({ id:m.id, lat:m.lat, lng:m.lng, title:m.title, detail:`${m.type} · ${m.quantity} · ${m.city}` }))} className="w-full"/><p className="mt-2 text-xs text-muted-foreground">المواد التجريبية تظهر بمواقع تقريبية، والمواد التي تضيفها تظهر في موقع الإحداثيات الذي اخترته.</p></div>
      <div className="mt-10 flex items-center justify-between"><h2 className="text-xl font-extrabold">المواد المتاحة ({shown.length})</h2><span className="text-sm text-muted-foreground">مرتبة حسب الأقرب</span></div><div className="mt-5 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{shown.map((m) => <MaterialCard key={m.id} material={m} />)}</div>{shown.length === 0 && <div className="mt-6 border border-border bg-muted p-10 text-center text-muted-foreground">لا توجد مواد مطابقة لبحثك.</div>}
      <section className="mt-12 border border-primary/30 bg-secondary p-6"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-center"><div className="flex gap-4"><Sparkles className="mt-1 size-7 shrink-0 text-primary"/><div><h2 className="font-extrabold">المطابقة الذكية</h2><p className="mt-2 max-w-2xl text-sm leading-7 text-muted-foreground">لديك احتياج محدد؟ تساعدك وصال في المطابقة بين المادة والكمية والحالة والموقع، ويمكن تقسيم الكمية على أكثر من جهة.</p></div></div><Button asChild><Link to="/mwan-link/matching">عرض اقتراح المطابقة</Link></Button></div></section>
    </div></MwanShell>;
}

export function MaterialDetails({ materialId }: { materialId: string }) {
  const { materials, completedIds } = useMaterials();
  const material = materials.find((m) => m.id === materialId);
  const navigate = useNavigate();
  const [confirm, setConfirm] = useState(false);
  if (!material) return <MwanShell><PageIntro title="المادة غير موجودة" crumbs={["وصال", "المواد المتاحة"]} /><div className="mx-auto max-w-3xl px-4 py-12 text-center"><p className="text-muted-foreground">قد تكون المادة محفوظة في متصفح آخر أو لم تعد متاحة.</p><Button asChild className="mt-5"><Link to="/mwan-link/materials">العودة إلى المواد</Link></Button></div></MwanShell>;
  const userAdded = material.id.startsWith("user-");
  const completed = completedIds.includes(material.id);
  return <MwanShell><PageIntro title="تفاصيل المادة" crumbs={["وصال", "المواد المتاحة", material.type]} /><div className="mx-auto grid max-w-7xl gap-8 px-4 py-10 sm:px-6 lg:grid-cols-[1.35fr_.65fr] lg:px-8"><div><img src={material.image} alt={material.title} width={1200} height={800} className="aspect-[16/9] w-full rounded-lg object-cover"/><div className="mt-4 grid grid-cols-4 gap-2">{[1,2,3,4].map((i) => <img key={i} src={material.image} alt={`صورة ${i} للمادة`} loading="lazy" width={1200} height={800} className="aspect-square w-full rounded-md object-cover"/>)}</div><section className="mt-8 border-t border-border pt-7"><h2 className="text-xl font-extrabold">وصف المنتج</h2><p className="mt-3 leading-8 text-muted-foreground">{material.description || `${material.title} بحالة ${material.condition}، مفروزة ومخزنة في موقع المنشأة. مناسبة لإعادة الاستخدام الصناعي بعد معاينة المستهلك.`}</p></section><section className="mt-8 border border-border bg-card p-6"><h2 className="flex items-center gap-2 text-lg font-extrabold"><ShieldCheck className="text-primary"/>التحقق</h2><p className="mt-2 text-sm text-muted-foreground">يوضح هذا القسم ما تم التحقق منه لهذه المادة.</p><div className="mt-5 grid gap-4 text-sm sm:grid-cols-2">{(userAdded ? ["بيانات المادة أدخلها المستخدم", "الصورة مرفوعة مع الإعلان", ...(material.verified === "تحليل بصري أولي" ? ["يوجد تقييم بصري أولي"] : ["لم يجر تحليل بصري"]) ] : ["نوع المادة مؤكد من المنتج", "الصور مرفوعة من المنتج", "تحليل بصري بالذكاء الاصطناعي", "بيانات المنشأة متحققة"]).map((x) => <span key={x} className="flex gap-2"><CheckCircle2 className="size-5 shrink-0 text-success"/>{x}</span>)}<span className="flex gap-2 text-muted-foreground"><Circle className="size-5 shrink-0"/>التحقق الميداني: غير متوفر</span></div><p className="mt-5 bg-muted p-4 text-xs leading-6 text-muted-foreground">التحليل البصري تقييم أولي للخصائص الظاهرة في الصور، ولا يضمن الجودة ولا يحدد الوزن الفعلي.</p></section></div>
    <aside><Card className="sticky top-28 border-border shadow-card"><CardContent className="p-6"><div className="flex items-center justify-between gap-3"><Badge variant="secondary">{material.type}</Badge><span className="flex items-center gap-1 text-xs text-muted-foreground">{completed ? "مكتملة" : userAdded ? "إعلان جديد" : <><CheckCircle2 className="size-4 text-success"/>بيانات تجريبية</>}</span></div><h1 className="mt-5 text-xl font-extrabold leading-8">{material.title}</h1><strong className="mt-4 block text-2xl text-primary">{material.quantity}</strong><dl className="mt-6 grid gap-4 text-sm"><div className="flex justify-between border-b border-border pb-3"><dt className="text-muted-foreground">الحالة</dt><dd className="font-bold">{material.condition}</dd></div><div className="flex justify-between border-b border-border pb-3"><dt className="text-muted-foreground">الموقع</dt><dd className="font-bold">{material.city}</dd></div>{userAdded && <div className="flex justify-between border-b border-border pb-3"><dt className="text-muted-foreground">الإحداثيات</dt><dd className="font-bold" dir="ltr">{material.lat.toFixed(5)}, {material.lng.toFixed(5)}</dd></div>}{!userAdded && <><div className="flex justify-between border-b border-border pb-3"><dt className="text-muted-foreground">المنشأة</dt><dd className="font-bold">منشأة تجريبية</dd></div><div className="flex justify-between"><dt className="text-muted-foreground">حالة الترخيص</dt><dd className="font-bold text-muted-foreground">بيانات تجريبية</dd></div></>}</dl>{!userAdded && <p className="mt-5 text-xs leading-6 text-muted-foreground">النشاط: جمع ونقل النفايات. تظهر متطلبات الترخيص فقط للأنشطة المنظمة التي تتطلب ذلك.</p>}<Button className="mt-6 w-full" size="lg" disabled={completed} onClick={() => setConfirm(true)}>{completed ? "اكتمل الطلب" : "طلب المادة"}</Button></CardContent></Card></aside></div>
    <Dialog open={confirm} onOpenChange={setConfirm}><DialogContent dir="rtl"><DialogHeader><DialogTitle>تأكيد طلب المادة</DialogTitle><DialogDescription>سيتم إرسال الطلب للمنتج، ثم ربط خطوة النقل بمتطلبات منظومة موان.</DialogDescription></DialogHeader><div className="rounded-md bg-section p-4 text-sm"><strong>{material.title}</strong><p className="mt-2 text-muted-foreground">الكمية المطلوبة: {material.quantity}</p></div><div className="flex justify-end gap-2"><Button variant="outline" onClick={() => setConfirm(false)}>إلغاء</Button><Button onClick={() => navigate({ to: "/mwan-link/request", search: { materialId: material.id } })}>إرسال الطلب</Button></div></DialogContent></Dialog>
  </MwanShell>;
}

export function SmartMatching() {
  return <MwanShell><PageIntro title="اقتراح المطابقة الذكية" crumbs={["وصال", "المطابقة الذكية"]} description="اقتراح تجريبي مبني على المادة والكمية والحالة والموقع واحتياج المستهلك."/><div className="mx-auto max-w-5xl px-4 py-10 sm:px-6 lg:px-8"><div className="grid gap-5 md:grid-cols-[1fr_auto_1fr]"><Card><CardHeader><CardTitle>المادة المتاحة</CardTitle></CardHeader><CardContent><strong className="text-2xl text-primary">1,000 كجم خشب</strong><p className="mt-3 text-sm text-muted-foreground">حالة جيدة · جدة · منشأة متحققة</p></CardContent></Card><div className="grid place-items-center"><Sparkles className="size-9 text-primary"/></div><div className="grid gap-3"><Card><CardContent className="p-5"><div className="flex justify-between"><strong>احتياج منشأة أ</strong><span className="text-primary">500 كجم</span></div><p className="mt-2 text-xs text-muted-foreground">جدة · على بعد 4.2 كم · توافق 96%</p></CardContent></Card><Card><CardContent className="p-5"><div className="flex justify-between"><strong>احتياج منشأة ب</strong><span className="text-primary">500 كجم</span></div><p className="mt-2 text-xs text-muted-foreground">جدة · على بعد 7.8 كم · توافق 91%</p></CardContent></Card></div></div><div className="mt-7 border-r-4 border-success bg-section p-5"><strong className="text-success">مطابقة مكتملة للكمية</strong><p className="mt-2 text-sm leading-7 text-muted-foreground">يمكن توجيه كامل الكمية إلى احتياجين متوافقين بدل انتقالها لمسار التخلص.</p></div><div className="mt-7 flex justify-end"><Button asChild size="lg"><Link to="/mwan-link/materials/$materialId" params={{ materialId: "wood-jeddah" }}>مراجعة تفاصيل المادة</Link></Button></div></div></MwanShell>;
}

export function RequestJourney({ materialId }: { materialId?: string }) {
  const { materials, completedIds, completeMaterial } = useMaterials();
  const material = materials.find((item) => item.id === (materialId || "wood-jeddah")) || materials[0];
  const [stage, setStage] = useState(1); const [rating, setRating] = useState(0); const [reported, setReported] = useState(false);
  const steps = ["تم إرسال طلب المادة", "طلب النقل قيد المعالجة", "تم تأكيد النقل", "المادة في الطريق", "تم الاستلام"];
  const isCompleted = Boolean(material && (stage === 4 || completedIds.includes(material.id)));
  const shownStage = isCompleted ? 4 : stage;
  const advance = () => { const next = Math.min(stage + 1, 4); setStage(next); if (next === 4 && material) completeMaterial(material.id); };
  return <MwanShell><PageIntro title="متابعة الطلب والنقل" crumbs={["وصال", `طلب المادة: ${material?.title || "غير محددة"}`]} description="تابع مراحل الطلب حتى الاستلام. عند اكتمال الاستلام تُزال المادة من قائمة المتاح والخريطة."/><div className="mx-auto grid max-w-6xl gap-7 px-4 py-10 sm:px-6 lg:grid-cols-[1fr_.55fr] lg:px-8"><Card><CardHeader><CardTitle>حالة الطلب</CardTitle></CardHeader><CardContent><div className="space-y-1">{steps.map((step, i) => <div key={step} className="flex gap-4"><div className="flex flex-col items-center"><span className={`grid size-9 place-items-center rounded-full ${i <= shownStage ? "bg-primary text-primary-foreground" : "bg-muted text-muted-foreground"}`}>{i < shownStage || shownStage === 4 ? <Check className="size-4"/> : i === shownStage ? <Clock3 className="size-4"/> : <Circle className="size-4"/>}</span>{i < steps.length-1 && <span className={`h-12 w-px ${i < shownStage ? "bg-primary" : "bg-border"}`}/>}</div><div className="pt-2"><strong className={i <= shownStage ? "text-foreground" : "text-muted-foreground"}>{step}</strong>{i === shownStage && <p className="mt-1 text-xs text-primary">الحالة الحالية</p>}</div></div>)}</div>{!isCompleted && <Button className="mt-7" onClick={advance}>محاكاة الحالة التالية</Button>}{isCompleted && <p className="mt-6 rounded-md bg-secondary p-4 text-sm text-primary">اكتمل الاستلام، وأزيلت المادة من قائمة المواد المتاحة والخريطة.</p>}</CardContent></Card><div className="space-y-5"><Card><CardHeader><CardTitle className="text-base">ملخص الطلب</CardTitle></CardHeader><CardContent className="text-sm"><div className="flex justify-between border-b border-border py-3"><span className="text-muted-foreground">المادة</span><strong>{material?.title || "غير محددة"}</strong></div><div className="flex justify-between border-b border-border py-3"><span className="text-muted-foreground">الكمية</span><strong>{material?.quantity || "—"}</strong></div><div className="flex justify-between py-3"><span className="text-muted-foreground">النقل</span><strong>ضمن منظومة موان</strong></div></CardContent></Card>{shownStage === 4 && <Card><CardHeader><CardTitle>كيف كانت المادة؟</CardTitle></CardHeader><CardContent><div className="space-y-4">{["جودة المادة", "مطابقة الوصف", "مطابقة الكمية", "تجربة الاستلام"].map((label) => <div key={label} className="flex items-center justify-between gap-3"><span className="text-sm">{label}</span><div className="flex gap-1" dir="ltr">{[1,2,3,4,5].map((n) => <button key={n} onClick={() => setRating(n)} className={`text-xl ${n <= rating ? "text-warning" : "text-muted"}`} aria-label={`${n} نجوم`}>★</button>)}</div></div>)}</div><Button className="mt-6 w-full" disabled={!rating}>إرسال التقييم</Button><Button variant="ghost" className="mt-2 w-full text-destructive" onClick={() => setReported(true)}>{reported ? "تم استلام البلاغ" : "الإبلاغ عن اختلاف"}</Button></CardContent></Card>}</div></div></MwanShell>;
}
