import { Link, useNavigate } from "@tanstack/react-router";
import { Camera, ClipboardList, Eye, ImagePlus, MapPin, PackageCheck, Sparkles, Truck, Upload } from "lucide-react";
import { useEffect, useMemo, useRef, useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { MwanShell, PageIntro } from "./MwanShell";
import { LocationMap } from "./LocationMap";
import { imageFileToDataUrl, useMaterials } from "./materials-store";

type VisualAnalysis = { materialType?: string; condition?: string; visibleObservations?: string[]; reuseOptions?: string[]; safetyNotes?: string[]; confidence?: string; caveat?: string };

const Field = ({ label, children }: { label: string; children: React.ReactNode }) => <div><Label className="mb-2 block">{label}</Label>{children}</div>;

export function AddMaterial() {
  const navigate = useNavigate();
  const { addMaterial } = useMaterials();
  const [image, setImage] = useState<File | null>(null); const [analysis, setAnalysis] = useState<VisualAnalysis | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [location, setLocation] = useState<{lat:number;lng:number}|null>(null); const [mapOpen, setMapOpen] = useState(false);
  const [title, setTitle] = useState(""); const [type, setType] = useState(""); const [quantity, setQuantity] = useState(""); const [unit, setUnit] = useState("كجم"); const [condition, setCondition] = useState(""); const [description, setDescription] = useState("");
  const uploadRef = useRef<HTMLInputElement>(null); const cameraRef = useRef<HTMLInputElement>(null);
  const apiUrl = import.meta.env.VITE_AI_API_URL as string | undefined;
  const analyze = async () => { if (!image) return; if (!apiUrl) { setError("خدمة تحليل الصور لم تُفعّل بعد على الخادم. يمكنك حفظ المادة الآن وسيظهر التحليل عند تفعيل الخدمة."); return; } setBusy(true); setError(""); setAnalysis(null); try { const data = await new Promise<string>((resolve,reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result).split(",")[1] ?? ""); reader.onerror = reject; reader.readAsDataURL(image); }); const res = await fetch(`${apiUrl.replace(/\/$/,"")}/analyze`, { method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify({ image:{data,mime:image.type} }) }); const json = await res.json(); if (!res.ok) throw new Error(json.error || "تعذر تحليل الصورة الآن."); setAnalysis(json.analysis); } catch(e) { setError(e instanceof Error ? e.message : "حدث خطأ أثناء التحليل."); } finally { setBusy(false); } };
  const selectImage = (file?: File) => { setAnalysis(null); setError(""); if (!file) return; if (!["image/jpeg","image/png","image/webp"].includes(file.type)) { setError("ارفع صورة JPG أو PNG أو WebP."); return; } if (file.size > 10 * 1024 * 1024) { setError("حجم الصورة يجب ألا يتجاوز 10 ميغابايت."); return; } setImage(file); };
  const imageUrl = useMemo(() => image ? URL.createObjectURL(image) : "", [image]);
  useEffect(() => () => { if (imageUrl) URL.revokeObjectURL(imageUrl); }, [imageUrl]);
  const publish = async () => {
    if (!image || !location || !title.trim() || !type || !quantity || !condition) return;
    try {
      const storedImage = await imageFileToDataUrl(image);
      addMaterial({ id: `user-${Date.now()}`, title: title.trim(), type, quantity: `${quantity} ${unit}`, city: "موقع محدد", distance: "إحداثيات دقيقة", condition, images: 1, verified: analysis ? "تحليل بصري أولي" : "بانتظار التقييم", image: storedImage, lat: location.lat, lng: location.lng, description: description.trim() });
      navigate({ to: "/mwan-link/materials" });
    } catch (e) { setError(e instanceof Error ? e.message : "تعذر حفظ المادة. حاول بصورة أصغر."); }
  };
  const resultLists: { label: string; items?: string[] }[] = [
    { label: "ملاحظات مرئية", items: analysis?.visibleObservations },
    { label: "مسارات إعادة الاستخدام المحتملة", items: analysis?.reuseOptions },
    { label: "تنبيهات", items: analysis?.safetyNotes },
  ];
  return <MwanShell><PageIntro title="إضافة مادة جديدة" crumbs={["وصال", "منتج المواد", "إضافة مادة"]} description="أدخل بيانات المادة وارفع صورًا واضحة من زوايا مختلفة لتحسين دقة التقييم الأولي."/><div className="mx-auto max-w-5xl px-4 py-10 sm:px-6 lg:px-8">
    <div className="mb-8 flex items-center gap-2 overflow-x-auto">{["بيانات المادة", "الصور والتحليل", "التأكيد والنشر"].map((s,i) => <div key={s} className="flex min-w-max flex-1 items-center"><span className={`grid size-8 shrink-0 place-items-center rounded-full text-sm font-bold ${image || i === 0 ? "bg-primary text-primary-foreground" : "bg-muted text-muted-foreground"}`}>{i+1}</span><span className="mr-2 text-sm font-bold">{s}</span>{i<2 && <span className="mx-4 h-px flex-1 bg-border"/>}</div>)}</div>
    <Card><CardHeader><CardTitle>بيانات المادة</CardTitle></CardHeader><CardContent className="grid gap-5 sm:grid-cols-2"><Field label="اسم المادة"><Input value={title} onChange={e=>setTitle(e.target.value)} placeholder="مثال: طبالي خشبية"/></Field><Field label="نوع المادة"><select value={type} onChange={e=>setType(e.target.value)} className="h-9 w-full rounded-md border border-input bg-background px-3 text-sm"><option value="">اختر النوع</option><option>خشب</option><option>معدن</option><option>بلاستيك</option><option>كرتون</option><option>مواد بناء</option><option>أخرى</option></select></Field><Field label="الكمية"><Input value={quantity} onChange={e=>setQuantity(e.target.value)} type="number" min="0.1" step="any" placeholder="أدخل الكمية"/></Field><Field label="الوحدة / الوزن"><select value={unit} onChange={e=>setUnit(e.target.value)} className="h-9 w-full rounded-md border border-input bg-background px-3 text-sm"><option>كجم</option><option>طن</option><option>قطعة</option></select></Field><Field label="حالة المادة"><select value={condition} onChange={e=>setCondition(e.target.value)} className="h-9 w-full rounded-md border border-input bg-background px-3 text-sm"><option value="">اختر الحالة</option><option>جيدة</option><option>متوسطة</option><option>تحتاج معالجة</option></select></Field><Field label="موقع المادة"><Button type="button" variant="outline" className="w-full justify-start" onClick={() => setMapOpen(true)}><MapPin className="size-4"/>{location ? `${location.lat.toFixed(5)}, ${location.lng.toFixed(5)}` : "حدد الموقع على الخريطة"}</Button></Field><div className="sm:col-span-2"><Field label="وصف مختصر"><Textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="صف حالة المادة والاستخدام السابق…" className="min-h-28"/></Field></div></CardContent></Card>
    <Card className="mt-6"><CardHeader><CardTitle>صور المادة والتحليل</CardTitle></CardHeader><CardContent><input ref={uploadRef} className="hidden" type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={e => selectImage(e.target.files?.[0])}/><input ref={cameraRef} className="hidden" type="file" accept="image/jpeg,image/png,image/webp" capture="environment" onChange={e => selectImage(e.target.files?.[0])}/><div className="grid gap-4 sm:grid-cols-2"><button onClick={() => uploadRef.current?.click()} className="grid min-h-40 place-items-center rounded-lg border-2 border-dashed border-input bg-muted/40 p-5 text-center" aria-label="رفع صور المادة"><span><Upload className="mx-auto mb-3 text-primary"/><strong className="block text-sm">رفع صور من الجهاز</strong><span className="mt-2 block text-xs text-muted-foreground">يمكنك رفع أكثر من صورة من زوايا مختلفة (تحليل الصورة الأولى)</span></span></button><Button type="button" variant="outline" className="h-auto min-h-40 flex-col border-2 border-primary bg-secondary text-primary hover:bg-secondary/80" onClick={() => cameraRef.current?.click()}><Camera className="mb-2 size-8"/><strong>التقاط صورة للمادة</strong><span className="font-normal text-muted-foreground">استخدم كاميرا جهازك ثم ابدأ التحليل</span></Button></div>{image && <div className="mt-5 flex flex-wrap items-center gap-3 rounded-md bg-muted p-3"><img src={imageUrl} alt="معاينة الصورة المرفوعة" className="size-20 rounded object-cover"/><span className="min-w-0 flex-1 truncate text-sm">{image.name}</span><Button type="button" onClick={analyze} disabled={busy}>{busy ? "جارٍ تحليل الصورة…" : "تحليل الصورة"}</Button></div>}{error && <p role="alert" className="mt-4 rounded-md bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}{analysis && <div className="mt-6 border-r-4 border-primary bg-section p-5"><h3 className="flex items-center gap-2 font-bold"><Sparkles className="size-5 text-primary"/>نتيجة التحليل البصري</h3><dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><div><dt className="text-muted-foreground">نوع المادة المتوقع</dt><dd className="mt-1 font-bold">{analysis.materialType || "غير مؤكد"}</dd></div><div><dt className="text-muted-foreground">الحالة الظاهرية</dt><dd className="mt-1 font-bold">{analysis.condition || "غير مؤكدة"}</dd></div><div><dt className="text-muted-foreground">مستوى الثقة التقديري</dt><dd className="mt-1 font-bold">{analysis.confidence || "غير محدد"}</dd></div>{resultLists.map(({label,items}) => <div key={label}><dt className="text-muted-foreground">{label}</dt><dd className="mt-1 font-bold">{items?.length ? items.join("، ") : "لا تتوفر ملاحظات"}</dd></div>)}</dl><p className="mt-4 text-xs leading-6 text-muted-foreground">{analysis.caveat || "هذا تقييم بصري أولي فقط. لا يحدد الوزن أو التركيب الداخلي ولا يضمن صلاحية إنشائية. يلزم فحص مختص قبل الاستخدام."}</p></div>}</CardContent></Card>
    <div className="mt-7 flex justify-end"><Button size="lg" disabled={!image || !location || !title.trim() || !type || !quantity || !condition} onClick={publish}>{image && location && title && type && quantity && condition ? "تأكيد البيانات ونشر المادة" : "أكمل البيانات والصورة والموقع"}</Button></div>
    <Dialog open={mapOpen} onOpenChange={setMapOpen}><DialogContent dir="rtl" className="max-w-3xl"><DialogHeader><DialogTitle>حدد موقع المادة</DialogTitle><DialogDescription>انقر على الموقع الدقيق أو حدد موقعي باستخدام GPS، ثم اضغط حفظ.</DialogDescription></DialogHeader><LocationMap picker value={location} onSelect={setLocation} className="w-full"/><div className="flex items-center justify-between gap-3"><span className="text-xs text-muted-foreground">{location ? `الإحداثيات: ${location.lat.toFixed(6)}, ${location.lng.toFixed(6)}` : "لم يتم تحديد الموقع بعد"}</span><Button disabled={!location} onClick={() => setMapOpen(false)}>حفظ الموقع</Button></div></DialogContent></Dialog>
  </div></MwanShell>;
}

export function Dashboard() {
  const stats = [{label:"المواد المنشورة",value:"4",icon:PackageCheck},{label:"الطلبات النشطة",value:"3",icon:ClipboardList},{label:"طلبات النقل",value:"1",icon:Truck},{label:"إشعارات جديدة",value:"2",icon:Eye}];
  return <MwanShell><PageIntro title="لوحة التحكم" crumbs={["وصال", "لوحة التحكم"]} description="متابعة المواد والطلبات وحالة النقل من مكان واحد."/><div className="mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:px-8"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="text-xl font-extrabold">مرحبًا بك في وصال</h2><p className="mt-1 text-sm text-muted-foreground">حساب منشأة تجريبية</p></div><Button asChild><Link to="/mwan-link/add-material"><ImagePlus/>إضافة مادة</Link></Button></div><div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{stats.map(({label,value,icon:Icon}) => <Card key={label}><CardContent className="flex items-center gap-4 p-5"><span className="grid size-11 place-items-center rounded-md bg-secondary text-primary"><Icon/></span><div><strong className="text-2xl">{value}</strong><p className="text-xs text-muted-foreground">{label}</p></div></CardContent></Card>)}</div><div className="mt-8 grid gap-6 lg:grid-cols-[1.3fr_.7fr]"><Card><CardHeader><CardTitle>الطلبات الحالية</CardTitle></CardHeader><CardContent className="overflow-x-auto"><table className="w-full min-w-[560px] text-right text-sm"><thead className="bg-muted text-muted-foreground"><tr><th className="p-3">رقم الطلب</th><th className="p-3">المادة</th><th className="p-3">الكمية</th><th className="p-3">الحالة</th><th className="p-3">الإجراء</th></tr></thead><tbody><tr className="border-b border-border"><td className="p-3">ML-1042</td><td className="p-3 font-bold">خشب</td><td className="p-3">500 كجم</td><td className="p-3"><span className="text-warning">طلب النقل قيد المعالجة</span></td><td className="p-3"><Button asChild variant="link" size="sm"><Link to="/mwan-link/request">متابعة</Link></Button></td></tr><tr><td className="p-3">ML-1038</td><td className="p-3 font-bold">كرتون</td><td className="p-3">800 كجم</td><td className="p-3"><span className="text-success">تم الاستلام</span></td><td className="p-3"><Button variant="link" size="sm">التقييم</Button></td></tr></tbody></table></CardContent></Card><Card><CardHeader><CardTitle>الإشعارات</CardTitle></CardHeader><CardContent className="space-y-4"><div className="border-r-2 border-primary pr-3"><strong className="text-sm">طلب جديد على مادة الخشب</strong><p className="mt-1 text-xs text-muted-foreground">منذ 12 دقيقة</p></div><div className="border-r-2 border-success pr-3"><strong className="text-sm">تم تأكيد بيانات المنشأة</strong><p className="mt-1 text-xs text-muted-foreground">أمس</p></div><div className="border-r-2 border-warning pr-3"><strong className="text-sm">تحديث حالة النقل</strong><p className="mt-1 text-xs text-muted-foreground">منذ يومين</p></div></CardContent></Card></div></div></MwanShell>;
}
