import { Link, useNavigate } from "@tanstack/react-router";
import { Camera, CheckCircle2, ClipboardList, Eye, FileImage, ImagePlus, PackageCheck, ScanLine, Sparkles, Truck, Upload } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import wood from "@/assets/material-wood.jpg";
import { MwanShell, PageIntro } from "./MwanShell";

const Field = ({ label, children }: { label: string; children: React.ReactNode }) => <div><Label className="mb-2 block">{label}</Label>{children}</div>;

export function AddMaterial() {
  const navigate = useNavigate();
  const [camera, setCamera] = useState(false); const [captured, setCaptured] = useState(false); const [published, setPublished] = useState(false);
  const capture = () => { setCaptured(true); setCamera(false); };
  return <MwanShell><PageIntro title="إضافة مادة جديدة" crumbs={["موان لينك", "منتج النفايات", "إضافة مادة"]} description="أدخل بيانات المادة وارفع صورًا واضحة من زوايا مختلفة لتحسين دقة التقييم الأولي."/><div className="mx-auto max-w-5xl px-4 py-10 sm:px-6 lg:px-8">
    <div className="mb-8 flex items-center gap-2 overflow-x-auto">{["بيانات المادة", "الصور والتحليل", "التأكيد والنشر"].map((s,i) => <div key={s} className="flex min-w-max flex-1 items-center"><span className={`grid size-8 shrink-0 place-items-center rounded-full text-sm font-bold ${captured || i === 0 ? "bg-primary text-primary-foreground" : "bg-muted text-muted-foreground"}`}>{i+1}</span><span className="mr-2 text-sm font-bold">{s}</span>{i<2 && <span className="mx-4 h-px flex-1 bg-border"/>}</div>)}</div>
    <Card><CardHeader><CardTitle>بيانات المادة</CardTitle></CardHeader><CardContent className="grid gap-5 sm:grid-cols-2"><Field label="اسم المادة"><Input defaultValue={captured ? "طبالي خشبية قابلة لإعادة الاستخدام" : ""} placeholder="مثال: طبالي خشبية"/></Field><Field label="نوع المادة"><select className="h-9 w-full rounded-md border border-input bg-background px-3 text-sm"><option>اختر النوع</option><option selected={captured}>خشب</option><option>معدن</option><option>بلاستيك</option><option>كرتون</option><option>مواد بناء</option></select></Field><Field label="الكمية"><Input type="number" defaultValue="500"/></Field><Field label="الوحدة / الوزن"><select className="h-9 w-full rounded-md border border-input bg-background px-3 text-sm"><option>كجم</option><option>طن</option><option>قطعة</option></select></Field><Field label="حالة المادة"><select className="h-9 w-full rounded-md border border-input bg-background px-3 text-sm"><option>جيدة</option><option>متوسطة</option><option>تحتاج معالجة</option></select></Field><Field label="الموقع"><Input defaultValue="جدة"/></Field><div className="sm:col-span-2"><Field label="وصف مختصر"><Textarea defaultValue={captured ? "طبالي خشبية مخزنة في مكان جاف، تظهر عليها خدوش بسيطة ولا يوجد كسر ظاهر." : ""} placeholder="صف حالة المادة والاستخدام السابق…" className="min-h-28"/></Field></div></CardContent></Card>
    <Card className="mt-6"><CardHeader><CardTitle>صور المادة</CardTitle></CardHeader><CardContent><div className="grid gap-4 sm:grid-cols-2"><button className="grid min-h-40 place-items-center rounded-lg border-2 border-dashed border-input bg-muted/40 p-5 text-center" aria-label="رفع صور المادة"><span><Upload className="mx-auto mb-3 text-primary"/><strong className="block text-sm">رفع صور من الجهاز</strong><span className="mt-2 block text-xs text-muted-foreground">يمكنك رفع أكثر من صورة من زوايا مختلفة</span></span></button><Button variant="outline" className="h-auto min-h-40 flex-col border-2 border-primary bg-secondary text-primary hover:bg-secondary/80" onClick={() => setCamera(true)}><Camera className="mb-2 size-8"/><strong>تصوير المادة بالذكاء الاصطناعي</strong><span className="font-normal text-muted-foreground">واجهة تصوير تجريبية</span></Button></div>{captured && <div className="mt-6 grid gap-5 md:grid-cols-[240px_1fr]"><img src={wood} alt="صورة المادة الملتقطة" width={1200} height={800} className="aspect-[4/3] w-full rounded-md object-cover"/><div className="border-r-4 border-primary bg-section p-5"><h3 className="flex items-center gap-2 font-bold"><Sparkles className="size-5 text-primary"/>تحليل المادة بالذكاء الاصطناعي</h3><dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><div><dt className="text-muted-foreground">نوع المادة المتوقع</dt><dd className="mt-1 font-bold">خشب</dd></div><div><dt className="text-muted-foreground">الحالة الظاهرية</dt><dd className="mt-1 font-bold">جيدة</dd></div><div><dt className="text-muted-foreground">ملاحظات مرئية</dt><dd className="mt-1 font-bold">خدوش بسيطة</dd></div><div><dt className="text-muted-foreground">درجة الثقة</dt><dd className="mt-1 font-bold text-primary">92%</dd></div></dl><p className="mt-4 text-xs leading-6 text-muted-foreground">هذا تقييم أولي للخصائص الظاهرة فقط. لا يمكن تحديد الوزن أو ضمان الجودة من الصورة؛ أدخل الكمية وتحقق منها بوسيلة مناسبة.</p></div></div>}</CardContent></Card>
    <div className="mt-7 flex justify-end"><Button size="lg" disabled={!captured} onClick={() => setPublished(true)}>{captured ? "تأكيد البيانات ونشر المادة" : "أضف صورة لإكمال النشر"}</Button></div>
    <Dialog open={camera} onOpenChange={setCamera}><DialogContent dir="rtl"><DialogHeader><DialogTitle>تصوير المادة</DialogTitle><DialogDescription>ضع المادة كاملة داخل الإطار والتقط صورًا من زوايا متعددة.</DialogDescription></DialogHeader><div className="relative grid aspect-video place-items-center overflow-hidden rounded-lg bg-foreground text-background"><ScanLine className="size-20 opacity-30"/><span className="absolute inset-5 rounded-md border-2 border-dashed border-background/60"/><span className="absolute bottom-4 text-xs">كاميرا تجريبية</span></div><Button onClick={capture}><Camera/>التقاط الصورة وتحليلها</Button></DialogContent></Dialog>
    <Dialog open={published} onOpenChange={setPublished}><DialogContent dir="rtl"><div className="text-center"><CheckCircle2 className="mx-auto size-14 text-success"/><DialogHeader><DialogTitle className="mt-3">تم نشر المادة بنجاح</DialogTitle><DialogDescription>أصبحت المادة متاحة للمطابقة مع الجهات المناسبة، ويمكنك متابعتها من لوحة التحكم.</DialogDescription></DialogHeader><div className="mt-6 flex justify-center gap-2"><Button variant="outline" onClick={() => navigate({to:"/mwan-link/materials"})}>عرض المواد</Button><Button onClick={() => navigate({to:"/mwan-link/dashboard"})}>لوحة التحكم</Button></div></div></DialogContent></Dialog>
  </div></MwanShell>;
}

export function Dashboard() {
  const stats = [{label:"المواد المنشورة",value:"4",icon:PackageCheck},{label:"الطلبات النشطة",value:"3",icon:ClipboardList},{label:"طلبات النقل",value:"1",icon:Truck},{label:"إشعارات جديدة",value:"2",icon:Eye}];
  return <MwanShell><PageIntro title="لوحة التحكم" crumbs={["موان لينك", "لوحة التحكم"]} description="متابعة المواد والطلبات وحالة النقل من مكان واحد."/><div className="mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:px-8"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="text-xl font-extrabold">مرحبًا بك في موان لينك</h2><p className="mt-1 text-sm text-muted-foreground">حساب منشأة تجريبية</p></div><Button asChild><Link to="/mwan-link/add-material"><ImagePlus/>إضافة مادة</Link></Button></div><div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{stats.map(({label,value,icon:Icon}) => <Card key={label}><CardContent className="flex items-center gap-4 p-5"><span className="grid size-11 place-items-center rounded-md bg-secondary text-primary"><Icon/></span><div><strong className="text-2xl">{value}</strong><p className="text-xs text-muted-foreground">{label}</p></div></CardContent></Card>)}</div><div className="mt-8 grid gap-6 lg:grid-cols-[1.3fr_.7fr]"><Card><CardHeader><CardTitle>الطلبات الحالية</CardTitle></CardHeader><CardContent className="overflow-x-auto"><table className="w-full min-w-[560px] text-right text-sm"><thead className="bg-muted text-muted-foreground"><tr><th className="p-3">رقم الطلب</th><th className="p-3">المادة</th><th className="p-3">الكمية</th><th className="p-3">الحالة</th><th className="p-3">الإجراء</th></tr></thead><tbody><tr className="border-b border-border"><td className="p-3">ML-1042</td><td className="p-3 font-bold">خشب</td><td className="p-3">500 كجم</td><td className="p-3"><span className="text-warning">طلب النقل قيد المعالجة</span></td><td className="p-3"><Button asChild variant="link" size="sm"><Link to="/mwan-link/request">متابعة</Link></Button></td></tr><tr><td className="p-3">ML-1038</td><td className="p-3 font-bold">كرتون</td><td className="p-3">800 كجم</td><td className="p-3"><span className="text-success">تم الاستلام</span></td><td className="p-3"><Button variant="link" size="sm">التقييم</Button></td></tr></tbody></table></CardContent></Card><Card><CardHeader><CardTitle>الإشعارات</CardTitle></CardHeader><CardContent className="space-y-4"><div className="border-r-2 border-primary pr-3"><strong className="text-sm">طلب جديد على مادة الخشب</strong><p className="mt-1 text-xs text-muted-foreground">منذ 12 دقيقة</p></div><div className="border-r-2 border-success pr-3"><strong className="text-sm">تم تأكيد بيانات المنشأة</strong><p className="mt-1 text-xs text-muted-foreground">أمس</p></div><div className="border-r-2 border-warning pr-3"><strong className="text-sm">تحديث حالة النقل</strong><p className="mt-1 text-xs text-muted-foreground">منذ يومين</p></div></CardContent></Card></div></div></MwanShell>;
}