/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MwanLinkRouteImport } from './routes/mwan-link'
import { Route as MwanLinkIndexRouteImport } from './routes/mwan-link.index'
import { Route as MwanLinkAddMaterialRouteImport } from './routes/mwan-link.add-material'
import { Route as MwanLinkDashboardRouteImport } from './routes/mwan-link.dashboard'
import { Route as MwanLinkMatchingRouteImport } from './routes/mwan-link.matching'
import { Route as MwanLinkMaterialsRouteImport } from './routes/mwan-link.materials'
import { Route as MwanLinkRequestRouteImport } from './routes/mwan-link.request'
import { Route as MwanLinkMaterialsIndexRouteImport } from './routes/mwan-link.materials.index'
import { Route as MwanLinkMaterialsMaterialIdRouteImport } from './routes/mwan-link.materials.$materialId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MwanLinkRoute = MwanLinkRouteImport.update({
  id: '/mwan-link',
  path: '/mwan-link',
  getParentRoute: () => rootRouteImport,
} as any)
const MwanLinkIndexRoute = MwanLinkIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MwanLinkRoute,
} as any)
const MwanLinkAddMaterialRoute = MwanLinkAddMaterialRouteImport.update({
  id: '/add-material',
  path: '/add-material',
  getParentRoute: () => MwanLinkRoute,
} as any)
const MwanLinkDashboardRoute = MwanLinkDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => MwanLinkRoute,
} as any)
const MwanLinkMatchingRoute = MwanLinkMatchingRouteImport.update({
  id: '/matching',
  path: '/matching',
  getParentRoute: () => MwanLinkRoute,
} as any)
const MwanLinkMaterialsRoute = MwanLinkMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => MwanLinkRoute,
} as any)
const MwanLinkRequestRoute = MwanLinkRequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => MwanLinkRoute,
} as any)
const MwanLinkMaterialsIndexRoute = MwanLinkMaterialsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MwanLinkMaterialsRoute,
} as any)
const MwanLinkMaterialsMaterialIdRoute =
  MwanLinkMaterialsMaterialIdRouteImport.update({
    id: '/$materialId',
    path: '/$materialId',
    getParentRoute: () => MwanLinkMaterialsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mwan-link': typeof MwanLinkRouteWithChildren
  '/mwan-link/add-material': typeof MwanLinkAddMaterialRoute
  '/mwan-link/dashboard': typeof MwanLinkDashboardRoute
  '/mwan-link/matching': typeof MwanLinkMatchingRoute
  '/mwan-link/materials': typeof MwanLinkMaterialsRouteWithChildren
  '/mwan-link/request': typeof MwanLinkRequestRoute
  '/mwan-link/': typeof MwanLinkIndexRoute
  '/mwan-link/materials/$materialId': typeof MwanLinkMaterialsMaterialIdRoute
  '/mwan-link/materials/': typeof MwanLinkMaterialsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mwan-link/add-material': typeof MwanLinkAddMaterialRoute
  '/mwan-link/dashboard': typeof MwanLinkDashboardRoute
  '/mwan-link/matching': typeof MwanLinkMatchingRoute
  '/mwan-link/request': typeof MwanLinkRequestRoute
  '/mwan-link': typeof MwanLinkIndexRoute
  '/mwan-link/materials/$materialId': typeof MwanLinkMaterialsMaterialIdRoute
  '/mwan-link/materials': typeof MwanLinkMaterialsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mwan-link': typeof MwanLinkRouteWithChildren
  '/mwan-link/add-material': typeof MwanLinkAddMaterialRoute
  '/mwan-link/dashboard': typeof MwanLinkDashboardRoute
  '/mwan-link/matching': typeof MwanLinkMatchingRoute
  '/mwan-link/materials': typeof MwanLinkMaterialsRouteWithChildren
  '/mwan-link/request': typeof MwanLinkRequestRoute
  '/mwan-link/': typeof MwanLinkIndexRoute
  '/mwan-link/materials/$materialId': typeof MwanLinkMaterialsMaterialIdRoute
  '/mwan-link/materials/': typeof MwanLinkMaterialsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mwan-link'
    | '/mwan-link/add-material'
    | '/mwan-link/dashboard'
    | '/mwan-link/matching'
    | '/mwan-link/materials'
    | '/mwan-link/request'
    | '/mwan-link/'
    | '/mwan-link/materials/$materialId'
    | '/mwan-link/materials/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mwan-link/add-material'
    | '/mwan-link/dashboard'
    | '/mwan-link/matching'
    | '/mwan-link/request'
    | '/mwan-link'
    | '/mwan-link/materials/$materialId'
    | '/mwan-link/materials'
  id:
    | '__root__'
    | '/'
    | '/mwan-link'
    | '/mwan-link/add-material'
    | '/mwan-link/dashboard'
    | '/mwan-link/matching'
    | '/mwan-link/materials'
    | '/mwan-link/request'
    | '/mwan-link/'
    | '/mwan-link/materials/$materialId'
    | '/mwan-link/materials/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MwanLinkRoute: typeof MwanLinkRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mwan-link': {
      id: '/mwan-link'
      path: '/mwan-link'
      fullPath: '/mwan-link'
      preLoaderRoute: typeof MwanLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mwan-link/': {
      id: '/mwan-link/'
      path: '/'
      fullPath: '/mwan-link/'
      preLoaderRoute: typeof MwanLinkIndexRouteImport
      parentRoute: typeof MwanLinkRoute
    }
    '/mwan-link/add-material': {
      id: '/mwan-link/add-material'
      path: '/add-material'
      fullPath: '/mwan-link/add-material'
      preLoaderRoute: typeof MwanLinkAddMaterialRouteImport
      parentRoute: typeof MwanLinkRoute
    }
    '/mwan-link/dashboard': {
      id: '/mwan-link/dashboard'
      path: '/dashboard'
      fullPath: '/mwan-link/dashboard'
      preLoaderRoute: typeof MwanLinkDashboardRouteImport
      parentRoute: typeof MwanLinkRoute
    }
    '/mwan-link/matching': {
      id: '/mwan-link/matching'
      path: '/matching'
      fullPath: '/mwan-link/matching'
      preLoaderRoute: typeof MwanLinkMatchingRouteImport
      parentRoute: typeof MwanLinkRoute
    }
    '/mwan-link/materials': {
      id: '/mwan-link/materials'
      path: '/materials'
      fullPath: '/mwan-link/materials'
      preLoaderRoute: typeof MwanLinkMaterialsRouteImport
      parentRoute: typeof MwanLinkRoute
    }
    '/mwan-link/request': {
      id: '/mwan-link/request'
      path: '/request'
      fullPath: '/mwan-link/request'
      preLoaderRoute: typeof MwanLinkRequestRouteImport
      parentRoute: typeof MwanLinkRoute
    }
    '/mwan-link/materials/': {
      id: '/mwan-link/materials/'
      path: '/'
      fullPath: '/mwan-link/materials/'
      preLoaderRoute: typeof MwanLinkMaterialsIndexRouteImport
      parentRoute: typeof MwanLinkMaterialsRoute
    }
    '/mwan-link/materials/$materialId': {
      id: '/mwan-link/materials/$materialId'
      path: '/$materialId'
      fullPath: '/mwan-link/materials/$materialId'
      preLoaderRoute: typeof MwanLinkMaterialsMaterialIdRouteImport
      parentRoute: typeof MwanLinkMaterialsRoute
    }
  }
}

interface MwanLinkMaterialsRouteChildren {
  MwanLinkMaterialsMaterialIdRoute: typeof MwanLinkMaterialsMaterialIdRoute
  MwanLinkMaterialsIndexRoute: typeof MwanLinkMaterialsIndexRoute
}

const MwanLinkMaterialsRouteChildren: MwanLinkMaterialsRouteChildren = {
  MwanLinkMaterialsMaterialIdRoute: MwanLinkMaterialsMaterialIdRoute,
  MwanLinkMaterialsIndexRoute: MwanLinkMaterialsIndexRoute,
}

const MwanLinkMaterialsRouteWithChildren =
  MwanLinkMaterialsRoute._addFileChildren(MwanLinkMaterialsRouteChildren)

interface MwanLinkRouteChildren {
  MwanLinkAddMaterialRoute: typeof MwanLinkAddMaterialRoute
  MwanLinkDashboardRoute: typeof MwanLinkDashboardRoute
  MwanLinkMatchingRoute: typeof MwanLinkMatchingRoute
  MwanLinkMaterialsRoute: typeof MwanLinkMaterialsRouteWithChildren
  MwanLinkRequestRoute: typeof MwanLinkRequestRoute
  MwanLinkIndexRoute: typeof MwanLinkIndexRoute
}

const MwanLinkRouteChildren: MwanLinkRouteChildren = {
  MwanLinkAddMaterialRoute: MwanLinkAddMaterialRoute,
  MwanLinkDashboardRoute: MwanLinkDashboardRoute,
  MwanLinkMatchingRoute: MwanLinkMatchingRoute,
  MwanLinkMaterialsRoute: MwanLinkMaterialsRouteWithChildren,
  MwanLinkRequestRoute: MwanLinkRequestRoute,
  MwanLinkIndexRoute: MwanLinkIndexRoute,
}

const MwanLinkRouteWithChildren = MwanLinkRoute._addFileChildren(
  MwanLinkRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MwanLinkRoute: MwanLinkRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
